// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDltttGlYIr4Dv0WPaNBmYaMo8b1igTsKk',
    appId: '1:271843366719:android:7e603b1b4451d4f661658a',
    messagingSenderId: '271843366719',
    projectId: 'g-service-11b4a',
    storageBucket: 'g-service-11b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGU0bMh1BPsqzqHteEnwqBgf3j1O9xVas',
    appId: '1:271843366719:ios:e2e01d1f882a4dcd61658a',
    messagingSenderId: '271843366719',
    projectId: 'g-service-11b4a',
    storageBucket: 'g-service-11b4a.firebasestorage.app',
    androidClientId: '271843366719-79kjk30hob1jknpk3fganudaqu5n9ip3.apps.googleusercontent.com',
    iosClientId: '271843366719-60j4l586qto9epfsdqvl51ua8js366l1.apps.googleusercontent.com',
    iosBundleId: 'com.bg.gservice',
  );
}
